import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <nav className='navbar'>
          {/* <a className='logo' href="/" >Home</a>
          <a href="/list">List</a> */}
          <Link className='logo' href="/" >zzimBoard</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
